# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/discord_bot_intro',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/discord_bot_intro',
                'lib_path': 'discord_bot_intro'},
  'syms': {'discord_bot_intro.core': {'discord_bot_intro.core.foo': ('core.html#foo', 'discord_bot_intro/core.py')}}}
